language: dart
dart:
  - stable
os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # you need this source to get the right version of libstdc++6
    packages:
      - libstdc++6
      - fonts-droid
      - lcov
install:
  - echo 'Avoid default Travis CI install step' # this is to avoid an error with pub in Travis
before_script:
  - cd ..
  - git clone https://github.com/flutter/flutter.git
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:`pwd`/.pub-cache/bin:$PATH
  - flutter doctor
  - pub global activate coverage
script:
  - cd $TRAVIS_BUILD_DIR
  - bash test-coverage.sh
after_success: bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
cache:
  directories:
    - $HOME/.pub-cache