name: backend
description: The Ginko backend
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  logging:
  colorize:
  mysql1:
  nextcloud:
  crypto:
  meta:
  tuple:
  args:
  translations:
    path: ../translations
  models:
    path: ../models
  parsers:
    path: ../parsers

dev_dependencies:
  test: