name: ginko
base: core18
version: '1.2.3+13'
summary: The Ginko app
description: |
  The Ginko app
confinement: devmode
grade: devel
apps:
  ginko:
    command: ginko
    desktop: local/ginko.desktop
parts:
  desktop:
    plugin: dump
    source: snap
  assets:
    plugin: dump
    source: assets
  app:
    plugin: dump
    source: build
    stage-packages:
      - libx11-6
      - libxrandr2
      - libxcursor1
      - libxinerama1
      - libglu1-mesa
      - libgcc1
      - libstdc++6
      - libtinfo5
      - zlib1g