name: parsers
description: The Ginko parsers
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  html: ^0.14.0+3
  dio: ^3.0.4
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  html_unescape: ^1.0.1+3
  tuple: ^1.0.3
  csv: ^4.0.3
  models:
    path: ../models

dev_dependencies:
  test: ^1.8.0