name: parsers
description: The Ginko parsers
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  html:
  dio:
  dio_cookie_manager:
  cookie_jar:
  html_unescape:
  tuple:
  models:
    path: ../models

dev_dependencies:
  test: