name: ginko
description: The Ginko app
version: 1.0.1+2
author: jld3103

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http:
  crypto: ^2.1.3
  flutter_svg: ^0.14.1
  intl: ^0.16.0
  sliding_up_panel: ^0.3.6
  firebase_messaging: ^5.1.6
  firebase_ml_vision: ^0.9.2+2
  image_picker: ^0.6.1+4
  shared_preferences: ^0.5.3+4
  material_design_icons_flutter: ^3.2.4495
  cached_network_image: ^1.1.1
  flutter_html: ^0.11.0
  url_launcher: ^5.1.4
  share: ^0.6.2+1
  models:
    path: ../models
  translations:
    path: ../translations

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  test: ^1.6.3
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: # TODO: Until https://github.com/dart-lang/http/pull/286 is merged
    git:
      url: https://github.com/jld3103/http.git
      ref: fix-multipart-file

flutter:
  uses-material-design: true
  assets:
    - images/logo_green.svg
    - images/logo_green.png
    - images/logo_white.svg
    - web/manifest.json
    - web/firebase-messaging.js
    - web/firebase-messaging-sw.js
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto.ttf
          weight: 400
    - family: MaterialIcons
      fonts:
        - asset: fonts/Material-Icons/MaterialIcons-Regular.ttf
          weight: 400