name: app
description: The Ginko app
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+1
  crypto: ^2.0.6
  flutter_svg: ^0.13.0+1
  intl: ^0.15.8
  sliding_up_panel: ^0.3.4
  models:
    path: ../models

dev_dependencies:
  flutter_launcher_icons: ^0.7.2

dependecy_overrides:
  http: # TODO: Until https://github.com/dart-lang/http/pull/286 is merged
    git:
      url: https://github.com/jld3103/http.git
      ref: fix-multipart-file

flutter:
  uses-material-design: true
  assets:
    - images/logo_green.svg
    - images/logo_white.svg
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: MaterialIcons
      fonts:
        - asset: fonts/Material-Icons/MaterialIcons-Regular.ttf
          weight: 400

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo_green.png"