name: ginko
description: The Ginko app
version: 1.2.1+11
author: jld3103

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  crypto: ^2.1.3
  flutter_svg: ^0.14.3
  intl: ^0.16.0
  sliding_up_panel: ^0.3.6
  firebase_messaging: ^5.1.6
  firebase_ml_vision: ^0.9.3
  image_picker: ^0.6.1+10
  shared_preferences: ^0.5.4
  material_design_icons_flutter:
  cached_network_image: ^2.0.0-rc
  flutter_html: ^0.11.0
  url_launcher: ^5.2.5
  url_launcher_web:
    git:
      url: git://github.com/flutter/plugins.git
      path: packages/url_launcher/url_launcher_web
  share: ^0.6.3+1
  transparent_image: ^1.0.0
  after_layout: ^1.0.7+2
  nextcloud: ^1.0.8
  open_file: ^2.0.3
  path_provider: ^1.4.0
  filesize: ^1.0.4
  timeago: ^2.0.21
  file_picker: ^1.4.2
  downloads_path_provider:
    git:
      url: git://github.com/jld3103/downloads_path_provider.git
  dio: ^3.0.4
  version: ^1.0.3
  js: ^0.6.1+1
  models:
    path: ../models
  translations:
    path: ../translations

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  test: ^1.6.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/logo_green.svg
    - images/logo_green.png
    - images/logo_green_192x192.png
    - images/logo_white.svg
    - pubspec.yaml
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto.ttf
          weight: 400
