name: app
description: The Ginko app
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  crypto: ^2.0.6
  flutter_svg: ^0.14.0
  intl: ^0.15.8
  sliding_up_panel: ^0.3.4
  firebase_messaging: ^5.1.2
  firebase_ml_vision: ^0.9.2
  image_picker: ^0.6.1+2
  models:
    path: ../models
  translations:
    path: ../translations
  flutter_platform:
  flutter_platform_storage:

dev_dependencies:
  flutter_launcher_icons: ^0.7.2+1
  test: ^1.6.3
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: # TODO: Until https://github.com/dart-lang/http/pull/286 is merged
    git:
      url: https://github.com/jld3103/http.git
      ref: fix-multipart-file
  flutter_platform:
    path: ../packages/flutter_platform
  flutter_platform_storage:
    path: ../packages/flutter_platform_storage

flutter:
  uses-material-design: true
  assets:
    - images/logo_green.svg
    - images/logo_green.png
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto.ttf
          weight: 400
    - family: MaterialIcons
      fonts:
        - asset: fonts/Material-Icons/MaterialIcons-Regular.ttf
          weight: 400