name: server
description: The Ginko server
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  html: ^0.14.0+2
  intl: ^0.16.0
  crypto: ^2.1.1+1
  dio: ^2.1.13
  cookie_jar: ^1.0.1
  html_unescape: ^1.0.1+3
  models:
    path: ../models
  translations:
    path: ../translations

dev_dependencies:
  test: ^1.6.5