name: server
description: The Ginko server
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  html: ^0.14.0+2
  intl: ^0.15.8
  crypto: ^2.0.6
  dio: ^2.1.10
  cookie_jar: ^1.0.0
  models:
    path: ../models
  translations:
    path: ../translations

dev_dependencies:
  test: ^1.6.5