name: server
description: The Ginko server
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  html: ^0.14.0+3
  intl: ^0.16.0
  crypto: ^2.1.3
  dio: ^3.0.3
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  html_unescape: ^1.0.1+3
  nextcloud: ^1.0.7
  models:
    path: ../models
  translations:
    path: ../translations

dev_dependencies:
  test: ^1.8.0