name: flutter_platform
description: A plugin to detect the platform on any platform. Mobile, Desktop, Web all included
version: 1.0.2+3
author: jld3103 <pub@2bad2c0.de>
homepage: https://github.com/jld3103/ginko/tree/master/packages/flutter_platform

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter