name: flutter_platform_storage
description: A plugin to access persistent storage on any platform. Mobile, Desktop, Web all included
version: 1.0.2+3
author: jld3103 <pub@2bad2c0.de>
homepage: https://github.com/jld3103/ginko/tree/master/packages/flutter_platform_storage

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_platform: ^1.0.2+3
  shared_preferences: ^0.5.3+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter