name: models
description: The Ginko data models
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  meta: ^1.1.7
  intl: ^0.16.0
  crypto: ^2.1.1+1

dev_dependencies:
  test: ^1.6.5