name: models
description: The Ginko data models
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  meta:
  intl:
  crypto:
  translations:
    path: ../translations

dev_dependencies:
  test: